'use client'

import Link from 'next/link'

const COLORS = {
  primary: '#4338CA',
  accent: '#14B8A6',
  nearBlack: '#111827',
  offWhite: '#F8FAFC',
  muted: '#64748B',
  cardBg: '#FFFFFF',
  border: '#E2E8F0',
}

export default function AuditPage() {
  const auditEntries = [
    { hash: '0x7f3a9c...', action: 'Assignment generated', paper: 'P-2026-0847', reviewers: '3 anonymous', proof: 'DPoP + policy v4' },
    { hash: '0x2b1de4...', action: 'Conflict verified', paper: 'P-2026-0912', reviewers: '2 anonymous', proof: 'Encrypted declaration' },
    { hash: '0x9e8f12...', action: 'Roster finalized', paper: 'P-2026-0847', reviewers: '3 anonymous', proof: 'Collective signature' },
  ]

  return (
    <div style={{ minHeight: '100vh', background: COLORS.offWhite, padding: '32px 24px' }}>
      <div style={{ maxWidth: '860px', margin: '0 auto' }}>
        <Link href="/home" style={{ color: COLORS.muted, fontSize: '14px', textDecoration: 'none' }}>← Back to dashboard</Link>
        
        <div style={{ marginTop: '16px', marginBottom: '24px' }}>
          <div style={{ fontSize: '28px', fontWeight: 700, color: COLORS.nearBlack }}>Public Audit Trail</div>
          <div style={{ color: COLORS.muted, marginTop: '6px' }}>Anyone can verify that no single editor controlled these assignments</div>
        </div>

        <div style={{ background: COLORS.cardBg, border: `1px solid ${COLORS.border}`, borderRadius: '16px', overflow: 'hidden' }}>
          <div style={{ padding: '16px 24px', borderBottom: `1px solid ${COLORS.border}`, background: '#F8FAFC', fontSize: '13px', fontWeight: 600, color: COLORS.muted }}>
            Cryptographic Assignment Log — Verifiable by any outsider
          </div>
          
          {auditEntries.map((entry, idx) => (
            <div key={idx} style={{ padding: '18px 24px', borderBottom: idx < auditEntries.length - 1 ? `1px solid ${COLORS.border}` : 'none', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>
                <div style={{ fontFamily: 'monospace', fontSize: '12px', color: COLORS.accent, background: '#F0F9FF', padding: '4px 8px', borderRadius: '6px' }}>{entry.hash}</div>
                <div>
                  <div style={{ fontWeight: 600, color: COLORS.nearBlack }}>{entry.action}</div>
                  <div style={{ fontSize: '13px', color: COLORS.muted }}>{entry.paper} • {entry.reviewers}</div>
                </div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <div style={{ fontSize: '12px', color: COLORS.muted }}>Proof</div>
                <div style={{ fontSize: '13px', fontWeight: 600, color: COLORS.primary }}>{entry.proof}</div>
              </div>
            </div>
          ))}
        </div>

        <div style={{ marginTop: '24px', padding: '16px', background: '#FEF3C7', borderRadius: '12px', fontSize: '13px', color: '#92400E' }}>
          This log is generated by Tide-enforced policy. No administrator can alter entries after the fact.
        </div>
      </div>
    </div>
  )
}
